In [1]:
import os
import pandas as pd
import uuid

In [2]:
df_paths = [
    'token_data_0_20000.tsv',
    'token_data_20000_40000.tsv',
    'token_data_40000_60000.tsv',
    'token_data_60000_80000.tsv',
    'token_data_80000_100000.tsv',
    'token_data_100000_120000.tsv',
    'token_data_120000_140000.tsv',
    'token_data_140000_160000.tsv',
    'token_data_160000_180000.tsv',
    'token_data_180000_200000.tsv',
]
# save_path = 'token_data_0_to_120000.tsv'
# save_path = 'token_data_0_to_100000.tsv'
# save_path = 'token_data_0_to_20000.tsv'
# save_path = 'token_data_0_to_40000.tsv'
# save_path = 'token_data_0_to_60000.tsv'
# save_path = 'token_data_0_to_80000.tsv'
# save_path = 'token_data_0_to_140000.tsv'
# save_path = 'token_data_0_to_160000.tsv'
# save_path = 'token_data/token_data_0_to_180000.tsv'
save_path = 'token_data/token_data_0_to_200000.tsv'

token_dir = '/Users/stevie/repos/lingo_kit_combined/lingo_kit_data/word_analysis/datasets/tatoeba/token_data'
df = pd.DataFrame()
for df_path in df_paths: 
    temp = pd.read_csv(os.path.join(token_dir, df_path), sep='\t')
    # print(df_path, len(temp), temp.columns)
    df = pd.concat([df, temp], axis=0, ignore_index=True)
# print(len(df))
df.drop_duplicates(subset=['token_hash'], inplace=True)
len(df), df.columns

(33424,
 Index(['token_hash', 'word', 'lemma', 'pos', 'xpos', 'deprel', 'count',
        'sentences', 'group_hash', 'group_count', 'group_pct', 'word_pct'],
       dtype='object'))

In [3]:
def get_group_hash(lemma, pos):
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, f"{lemma}-{pos}"))
df['group_hash'] = df.apply(lambda row: get_group_hash(row['lemma'], row['pos']), axis=1)

In [4]:
group_counts = {}
for group in df['group_hash'].unique():
    mask = df['group_hash'] == group
    group_df = df[mask]
    df.loc[mask, 'group_count'] = group_df['count'].sum()
    group_counts[group] = group_df['count'].sum()

In [5]:
df['group_pct'] = df['group_count'] / df['count'].sum()
df['word_pct'] = df['count'] / df['count'].sum()

In [6]:
df.sort_values(by=['group_pct', 'word_pct'], ascending=False, inplace=True)

In [7]:
print(len(df))
df = df[df['pos'] != 'PROPN']
print(len(df))

33424
29690

In [8]:
df.to_csv(save_path, sep='\t', index=False)

In [9]:
df[df['lemma'] == 'essere'][['word', 'pos', 'lemma']]

          word   pos   lemma
7            è   AUX  essere
8         sono   AUX  essere
9          era   AUX  essere
10      essere   AUX  essere
11       stato   AUX  essere
...        ...   ...     ...
56360    sarei  VERB  essere
75718  esagero  VERB  essere
5964    esseri  NOUN  essere
6013    essere  NOUN  essere
21772      eri  PRON  essere

[114 rows x 3 columns]

In [10]:
word = 'gli'
df[df['word'] == 'gli'][['word', 'pos', 'lemma']]

     word   pos lemma
5     gli   DET    il
1100  gli  PRON   gli